GET http://localhost:9001/

###
GET http://localhost:9001/vocabularies

###
GET http://localhost:9001/tests


###
POST http://localhost:9001/tests
content-type: application/json

{
  "title": "Petting 🦕"
}

###
POST http://localhost:9001/search/accommodation/1000
content-type: application/json

{
  "name": "Petting 🦕",
  "address": "Tokyo"
}